name: 'GitHub Action for Firebase'
author: 'Jeremy Shore'
description: 'Wraps the firebase-tools CLI to enable common commands.'
branding:
  icon: 'package'
  color: 'gray-dark'
inputs:
  isEmulator:
    description: 'Configure for Emulation'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'